import java.io.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * SerFileInspector
 * ----------------
 * A diagnostic console tool that deserializes a .ser file containing a
 * UserData object and prints a detailed inspection report.
 *
 * Usage:
 *   java SerFileInspector <path-to-file.ser>
 *
 * Example:
 *   java SerFileInspector user_1042.ser
 */
public class SerFileInspector {

    // Separator widths for formatting
    private static final int WIDE  = 60;
    private static final int NARROW = 40;

    private static final DateTimeFormatter DATE_FMT =
            DateTimeFormatter.ofPattern("MMMM d, yyyy");

    public static void main(String[] args) {

        printBanner();

        // ── Argument check ─────────────────────────────────────────────
        if (args.length == 0) {
            printError("No file path provided.");
            System.out.println("  Usage: java SerFileInspector <path-to-file.ser>");
            System.out.println();
            System.exit(1);
        }

        String filePath = args[0];
        File file = new File(filePath);

        // ── File system checks ─────────────────────────────────────────
        printSection("File System Check");
        checkFile(file);

        // ── Deserialization ────────────────────────────────────────────
        printSection("Deserialization");
        UserData user = deserialize(file);

        // ── Field Inspection ───────────────────────────────────────────
        if (user != null) {
            printSection("Field Inspection");
            inspectFields(user);

            printSection("Validation Report");
            runValidation(user);
        }

        printFooter();
    }

    // ══════════════════════════════════════════════════════════════════
    //  FILE SYSTEM CHECK
    // ══════════════════════════════════════════════════════════════════

    private static void checkFile(File file) {
        printField("Provided path",  file.getPath());
        printField("Absolute path",  file.getAbsolutePath());
        printField("File exists",    yesNo(file.exists()));

        if (!file.exists()) {
            printWarn("File does not exist at the given path. Check for typos or a missing upload.");
            System.out.println();
            System.exit(2);
        }

        printField("Is a file",      yesNo(file.isFile()));
        printField("Readable",       yesNo(file.canRead()));
        printField("Size",           file.length() + " bytes");

        // Warn on empty file
        if (file.length() == 0) {
            printWarn("File is empty (0 bytes). Serialized data cannot be read from an empty file.");
            System.out.println();
            System.exit(3);
        }

        // Warn if extension is not .ser
        if (!file.getName().toLowerCase().endsWith(".ser")) {
            printWarn("File does not have a .ser extension. Proceeding anyway, but verify the file type.");
        }

        printOk("File looks accessible.");
        System.out.println();
    }

    // ══════════════════════════════════════════════════════════════════
    //  DESERIALIZATION
    // ══════════════════════════════════════════════════════════════════

    private static UserData deserialize(File file) {
        System.out.println("  Attempting to deserialize as: UserData");
        System.out.println();

        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(file))) {

            Object obj = ois.readObject();

            printField("Deserialized type", obj.getClass().getName());

            if (obj instanceof UserData) {
                printOk("Object is a valid UserData instance.");
                System.out.println();
                return (UserData) obj;
            } else {
                printWarn("Object deserialized successfully, but it is NOT a UserData instance.");
                printWarn("Actual type: " + obj.getClass().getName());
                printWarn("This file may have been generated by a different version of the application.");
                System.out.println();
                return null;
            }

        } catch (InvalidClassException e) {
            printError("InvalidClassException — serialVersionUID mismatch.");
            System.out.println("  >> The file was serialized with a different version of UserData.");
            System.out.println("  >> Local  serialVersionUID : (see UserData.java)");
            System.out.println("  >> Detail : " + e.getMessage());

        } catch (StreamCorruptedException e) {
            printError("StreamCorruptedException — the file header is not a valid Java serialization stream.");
            System.out.println("  >> The file may be corrupted, truncated, or is not a .ser file at all.");
            System.out.println("  >> Detail : " + e.getMessage());

        } catch (ClassNotFoundException e) {
            printError("ClassNotFoundException — UserData class not found on classpath.");
            System.out.println("  >> Ensure UserData.class is compiled and on the same classpath.");
            System.out.println("  >> Detail : " + e.getMessage());

        } catch (EOFException e) {
            printError("EOFException — unexpected end of file reached.");
            System.out.println("  >> The file may be truncated or incomplete.");

        } catch (IOException e) {
            printError("IOException — could not read the file.");
            System.out.println("  >> Detail : " + e.getMessage());
        }

        System.out.println();
        return null;
    }

    // ══════════════════════════════════════════════════════════════════
    //  FIELD INSPECTION
    // ══════════════════════════════════════════════════════════════════

    private static void inspectFields(UserData user) {

        // Name
        printRawField("name",
                user.getName(),
                user.getName() == null ? "NULL" : "\"" + user.getName() + "\"");

        // Birthday
        LocalDate bday = user.getBirthday();
        String bdayRaw    = bday == null ? "NULL" : bday.toString();
        String bdayPretty = bday == null ? "NULL" : bday.format(DATE_FMT)
                + " (age " + calculateAge(bday) + ")";
        printRawField("birthday", bdayRaw, bdayPretty);

        // ID Number
        printRawField("idNumber",
                String.valueOf(user.getIdNumber()),
                String.valueOf(user.getIdNumber()));

        // PIN Code
        String pin = user.getPinCode();
        String pinDisplay = pin == null ? "NULL"
                : pin.length() <= 2
                    ? pin   // show very short pins as-is for debugging
                    : pin.substring(0, 2) + "****"; // mask middle digits
        printRawField("pinCode",
                pin == null ? "NULL" : "length=" + pin.length() + ", starts with " + pinDisplay,
                pin == null ? "NULL" : pinDisplay + " (masked)");

        System.out.println();
    }

    private static long calculateAge(LocalDate birthday) {
        return java.time.temporal.ChronoUnit.YEARS.between(birthday, LocalDate.now());
    }

    // ══════════════════════════════════════════════════════════════════
    //  VALIDATION
    // ══════════════════════════════════════════════════════════════════

    private static void runValidation(UserData user) {
        int issues = 0;

        issues += validate("Name is non-null and non-blank",
                user.isNameValid(),
                "Name is null or blank — this field is required.");

        issues += validate("Birthday is non-null and not in the future",
                user.isBirthdayValid(),
                user.getBirthday() == null
                    ? "Birthday is null."
                    : "Birthday is in the future (" + user.getBirthday() + "). Verify the date.");

        issues += validate("ID number is a positive integer",
                user.isIdValid(),
                "ID number is " + user.getIdNumber() + " — must be > 0.");

        issues += validate("PIN is exactly 6 numeric digits",
                user.isPinValid(),
                user.getPinCode() == null
                    ? "PIN is null."
                    : "PIN '" + user.getPinCode() + "' is invalid — must be exactly 6 digits (0-9).");

        System.out.println();
        System.out.println("  " + repeat("─", NARROW));
        if (issues == 0) {
            printOk("All validation checks passed. This file looks well-formed.");
        } else {
            printWarn(issues + " validation issue(s) found. See details above.");
        }
        System.out.println();
    }

    /**
     * Prints a single validation line.
     * @return 1 if the check failed, 0 if it passed.
     */
    private static int validate(String label, boolean passed, String failMessage) {
        if (passed) {
            System.out.printf("  [%s] %s%n", green("PASS"), label);
            return 0;
        } else {
            System.out.printf("  [%s] %s%n", red("FAIL"), label);
            System.out.printf("       %s%n", failMessage);
            return 1;
        }
    }

    // ══════════════════════════════════════════════════════════════════
    //  PRINT HELPERS
    // ══════════════════════════════════════════════════════════════════

    private static void printBanner() {
        System.out.println();
        System.out.println("  " + repeat("═", WIDE));
        System.out.println("   SER FILE INSPECTOR  —  UserData Diagnostic Tool");
        System.out.println("  " + repeat("═", WIDE));
        System.out.println();
    }

    private static void printSection(String title) {
        System.out.println("  ┌─ " + title + " " + repeat("─", Math.max(0, WIDE - title.length() - 4)) + "┐");
        System.out.println();
    }

    private static void printFooter() {
        System.out.println("  " + repeat("═", WIDE));
        System.out.println("   Inspection complete.");
        System.out.println("  " + repeat("═", WIDE));
        System.out.println();
    }

    private static void printField(String label, String value) {
        System.out.printf("  %-22s : %s%n", label, value);
    }

    private static void printRawField(String fieldName, String rawValue, String prettyValue) {
        System.out.println("  Field      : " + fieldName);
        System.out.println("  Raw value  : " + rawValue);
        System.out.println("  Formatted  : " + prettyValue);
        System.out.println();
    }

    private static void printOk(String msg) {
        System.out.println("  [" + green(" OK ") + "] " + msg);
    }

    private static void printWarn(String msg) {
        System.out.println("  [" + yellow("WARN") + "] " + msg);
    }

    private static void printError(String msg) {
        System.out.println("  [" + red("ERR ") + "] " + msg);
    }

    // ══════════════════════════════════════════════════════════════════
    //  ANSI COLOR HELPERS  (degrade gracefully if terminal lacks support)
    // ══════════════════════════════════════════════════════════════════

    private static boolean useColor() {
        // Disable color when output is piped or on Windows cmd without ANSI support
        String term = System.getenv("TERM");
        return System.console() != null
                || (term != null && !term.equalsIgnoreCase("dumb"));
    }

    private static String green(String s)  { return useColor() ? "\u001B[32m" + s + "\u001B[0m" : s; }
    private static String yellow(String s) { return useColor() ? "\u001B[33m" + s + "\u001B[0m" : s; }
    private static String red(String s)    { return useColor() ? "\u001B[31m" + s + "\u001B[0m" : s; }

    private static String yesNo(boolean b) { return b ? green("Yes") : red("No"); }

    private static String repeat(String ch, int n) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < n; i++) sb.append(ch);
        return sb.toString();
    }
}